version: '3'

services:
  app1:
    build: app
    container_name: app1
    command: sh -c "fastapi run"
    ports:
      - 8001:8000
    volumes:
      - ./app:/app

  app2:
    build: app
    container_name: app2
    command: sh -c "fastapi run"
    ports:
      - 8002:8000
    volumes:
      - ./app:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
